CREATE DATABASE QLCuaHangXeMay;
USE QLCuaHangXeMay;

CREATE TABLE XeMay (
    MaXe INT PRIMARY KEY AUTO_INCREMENT,
    TenXe VARCHAR(100) NOT NULL,
    HangXe VARCHAR(50),
    MauXe VARCHAR(50),
    GiaXe DECIMAL(15,2),
    SoLuong INT DEFAULT 0
);

CREATE TABLE KhachHang (
    MaKH INT PRIMARY KEY AUTO_INCREMENT,
    HoTen VARCHAR(100) NOT NULL,
    SDT VARCHAR(15),
    DiaChi VARCHAR(255)
);

CREATE TABLE HoaDon (
    MaHD INT PRIMARY KEY AUTO_INCREMENT,
    NgayLap DATE,
    MaKH INT,
    MaXe INT,
    SoLuong INT DEFAULT 1,
    TongTien DECIMAL(15,2),
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE,
    FOREIGN KEY (MaXe) REFERENCES XeMay(MaXe) ON DELETE CASCADE
);

